-- Expected Database Schema for NOEMI Survey Application
-- This file defines the complete expected schema that the application requires.
-- Used for schema drift detection and as source of truth for required tables.

-- Enable UUID generation extension if not already present
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- SURVEY & PARTICIPANT TABLES
-- ============================================================================

-- Participants table (Survey responses)
CREATE TABLE IF NOT EXISTS public.participants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text,
  marketing_opt_in boolean DEFAULT false,
  answers jsonb NOT NULL DEFAULT '{}',
  location_data jsonb,
  is_complete boolean DEFAULT false,
  progress text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ============================================================================  
-- DESIGN MANAGEMENT TABLES
-- ============================================================================

-- Design sets table (Groups of 4 quadrant images from same source)
CREATE TABLE IF NOT EXISTS public.design_sets (
  id text PRIMARY KEY, -- UUID from split_quadrants.py script
  source_image_url text NOT NULL,
  note text,
  created_at timestamptz DEFAULT now()
);

-- Individual designs table (Quadrant images for swipe game)
CREATE TABLE IF NOT EXISTS public.designs (
  id text PRIMARY KEY, -- UUID from split_quadrants.py script  
  set_id text NOT NULL REFERENCES public.design_sets(id) ON DELETE CASCADE,
  quadrant_index integer NOT NULL CHECK (quadrant_index >= 0 AND quadrant_index <= 3),
  image_url text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- ============================================================================
-- SWIPE GAME INTERACTION TABLES  
-- ============================================================================

-- Swipes table (User interactions with designs)
CREATE TABLE IF NOT EXISTS public.swipes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participant_id bigint NOT NULL REFERENCES public.participants(id) ON DELETE CASCADE,
  card_id text NOT NULL, -- References designs.id (allowing for both UUID and other formats)
  choice text CHECK (choice IN ('like','dislike','love','not_sure')) NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

-- Index for swipe lookups by participant
CREATE INDEX IF NOT EXISTS idx_swipes_participant ON public.swipes(participant_id);

-- Index for swipe lookups by design
CREATE INDEX IF NOT EXISTS idx_swipes_card ON public.swipes(card_id);  

-- Index for designs by set
CREATE INDEX IF NOT EXISTS idx_designs_set ON public.designs(set_id);

-- Unique constraint for design quadrant positioning within sets
CREATE UNIQUE INDEX IF NOT EXISTS idx_designs_set_quadrant 
  ON public.designs(set_id, quadrant_index);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE public.participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.design_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.designs ENABLE ROW LEVEL SECURITY; 
ALTER TABLE public.swipes ENABLE ROW LEVEL SECURITY;

-- Policy for participants: Users can insert their own data, read is unrestricted for analytics
DROP POLICY IF EXISTS "Allow anonymous insert participants" ON public.participants;
CREATE POLICY "Allow anonymous insert participants" ON public.participants 
  FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Allow read participants" ON public.participants;  
CREATE POLICY "Allow read participants" ON public.participants
  FOR SELECT TO anon USING (true);

-- Policy for design_sets: Read-only access for all users
DROP POLICY IF EXISTS "Allow read design_sets" ON public.design_sets;
CREATE POLICY "Allow read design_sets" ON public.design_sets
  FOR SELECT TO anon USING (true);

-- Policy for designs: Read-only access for all users  
DROP POLICY IF EXISTS "Allow read designs" ON public.designs;
CREATE POLICY "Allow read designs" ON public.designs
  FOR SELECT TO anon USING (true);

-- Policy for swipes: Users can insert swipes, read is unrestricted for analytics
DROP POLICY IF EXISTS "Allow anonymous insert swipes" ON public.swipes;
CREATE POLICY "Allow anonymous insert swipes" ON public.swipes
  FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Allow read swipes" ON public.swipes;
CREATE POLICY "Allow read swipes" ON public.swipes  
  FOR SELECT TO anon USING (true);

-- Allow authenticated users full access for admin operations
DROP POLICY IF EXISTS "Allow authenticated full access participants" ON public.participants;
CREATE POLICY "Allow authenticated full access participants" ON public.participants
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated full access design_sets" ON public.design_sets;  
CREATE POLICY "Allow authenticated full access design_sets" ON public.design_sets
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated full access designs" ON public.designs;
CREATE POLICY "Allow authenticated full access designs" ON public.designs
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated full access swipes" ON public.swipes;
CREATE POLICY "Allow authenticated full access swipes" ON public.swipes
  FOR ALL TO authenticated USING (true) WITH CHECK (true);