-- NOEMI Survey App - Expected Database Schema
-- This file serves as the source of truth for the application's database requirements
-- All changes should be backwards-compatible and non-destructive

-- ============================================================================
-- PARTICIPANTS TABLE
-- Stores survey participants and their responses
-- ============================================================================
create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  email text,
  marketing_opt_in boolean default false,
  answers jsonb not null default '{}',
  location_data jsonb,
  is_complete boolean default false,
  progress text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================================
-- SWIPES TABLE  
-- Stores user swipe actions for the design rating game
-- ============================================================================
create table if not exists public.swipes (
  id bigint generated by default as identity primary key,
  participant_id bigint not null references public.participants(id) on delete cascade,
  card_id text not null,  -- Can be bigint or uuid, using text for flexibility
  choice text check (choice in ('like','dislike','love','not_sure')) not null,
  created_at timestamptz default now()
);

-- ============================================================================
-- DESIGN_SETS TABLE
-- Stores groups of related design images (typically 4 quadrants from one source)
-- ============================================================================
create table if not exists public.design_sets (
  id uuid primary key default gen_random_uuid(),
  source_image_url text,
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================================
-- DESIGNS TABLE
-- Stores individual design images that users can rate/swipe
-- ============================================================================
create table if not exists public.designs (
  id uuid primary key default gen_random_uuid(),
  set_id uuid not null references public.design_sets(id) on delete cascade,
  quadrant_index integer not null check (quadrant_index >= 0 and quadrant_index <= 3),
  image_url text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================
create index if not exists idx_swipes_participant on public.swipes(participant_id);
create index if not exists idx_designs_set_id on public.designs(set_id);
create index if not exists idx_designs_quadrant on public.designs(quadrant_index);

-- ============================================================================
-- PERMISSIONS FOR ANONYMOUS USERS
-- Required for public survey and game functionality
-- ============================================================================
grant insert, select on public.participants to anon;
grant insert, select, delete on public.swipes to anon;
grant select on public.design_sets to anon;
grant select on public.designs to anon;

-- ============================================================================
-- PERMISSIONS FOR AUTHENTICATED USERS  
-- ============================================================================
grant insert, select, update, delete on public.participants to authenticated;
grant insert, select, update, delete on public.swipes to authenticated;
grant select on public.design_sets to authenticated;
grant select on public.designs to authenticated;

-- ============================================================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================================================
comment on table public.participants is 'Survey participants and their responses';
comment on table public.swipes is 'User swipe actions for design rating game';
comment on table public.design_sets is 'Groups of related design images for the swipe game';
comment on table public.designs is 'Individual design quadrants that users can swipe on';