create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  email text,
  marketing_opt_in boolean default false,
  answers jsonb not null default '{}',
  created_at timestamptz default now()
);
create table if not exists public.swipes (
  id bigint generated by default as identity primary key,
  participant_id bigint not null references public.participants(id) on delete cascade,
  card_id bigint not null,
  choice text check (choice in ('like','dislike','love','not_sure')) not null,
  created_at timestamptz default now()
);
create index if not exists idx_swipes_participant on public.swipes(participant_id);
