-- CRITICAL PRODUCTION FIX: Resolve 401 unauthorized and permission denied errors
-- This migration ensures the production Supabase database has correct RLS policies
-- Addresses: HTTP 401 and PostgreSQL 42501 "permission denied for schema public"

-- ============================================================================
-- STEP 1: ENSURE ALL REQUIRED TABLES EXIST
-- ============================================================================

-- Create participants table if it doesn't exist (should already exist from 0001_init.sql)
CREATE TABLE IF NOT EXISTS public.participants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text,
  marketing_opt_in boolean DEFAULT false,
  answers jsonb NOT NULL DEFAULT '{}',
  location_data jsonb,
  is_complete boolean DEFAULT false,
  progress text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create swipes table if it doesn't exist (should already exist from 0001_init.sql)  
CREATE TABLE IF NOT EXISTS public.swipes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participant_id bigint NOT NULL REFERENCES public.participants(id) ON DELETE CASCADE,
  card_id text NOT NULL, -- Changed from bigint to text to support UUID design IDs
  choice text CHECK (choice IN ('like','dislike','love','not_sure')) NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- ============================================================================
-- STEP 2: ENABLE ROW LEVEL SECURITY
-- ============================================================================

-- Enable RLS on participants table (safe if already enabled)
ALTER TABLE public.participants ENABLE ROW LEVEL SECURITY;

-- Enable RLS on swipes table (safe if already enabled)
ALTER TABLE public.swipes ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- STEP 3: REMOVE ANY CONFLICTING POLICIES (IDEMPOTENT)
-- ============================================================================

-- Remove any existing policies to avoid conflicts
DROP POLICY IF EXISTS "Allow anonymous insert participants" ON public.participants;
DROP POLICY IF EXISTS "Allow read participants" ON public.participants;  
DROP POLICY IF EXISTS "Allow authenticated full access participants" ON public.participants;

DROP POLICY IF EXISTS "Allow anonymous insert swipes" ON public.swipes;
DROP POLICY IF EXISTS "Allow read swipes" ON public.swipes;
DROP POLICY IF EXISTS "Allow authenticated full access swipes" ON public.swipes;

-- ============================================================================
-- STEP 4: CREATE CORRECT RLS POLICIES FOR PRODUCTION
-- ============================================================================

-- PARTICIPANTS TABLE POLICIES
-- Policy 1: Allow anonymous users to insert survey responses (critical for survey functionality)
CREATE POLICY "Allow anonymous insert participants" ON public.participants 
  FOR INSERT TO anon WITH CHECK (true);

-- Policy 2: Allow anonymous users to read participant data (for analytics and count queries)
CREATE POLICY "Allow read participants" ON public.participants
  FOR SELECT TO anon USING (true);

-- Policy 3: Allow authenticated users full access (for admin operations)
CREATE POLICY "Allow authenticated full access participants" ON public.participants
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- SWIPES TABLE POLICIES  
-- Policy 4: Allow anonymous users to insert swipe data (critical for game functionality)
CREATE POLICY "Allow anonymous insert swipes" ON public.swipes
  FOR INSERT TO anon WITH CHECK (true);

-- Policy 5: Allow anonymous users to read swipe data (for analytics)  
CREATE POLICY "Allow read swipes" ON public.swipes
  FOR SELECT TO anon USING (true);

-- Policy 6: Allow authenticated users full access (for admin operations)
CREATE POLICY "Allow authenticated full access swipes" ON public.swipes
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============================================================================
-- STEP 5: VERIFY POLICIES ARE CORRECTLY APPLIED
-- ============================================================================

-- Verification query - this will fail if policies aren't working
DO $$
DECLARE
  policy_count integer;
  table_rls_enabled boolean;
BEGIN
  -- Check that RLS is enabled on participants table
  SELECT rls_enabled INTO table_rls_enabled
  FROM information_schema.tables 
  WHERE table_schema = 'public' AND table_name = 'participants';
  
  IF NOT table_rls_enabled THEN
    RAISE EXCEPTION 'RLS not enabled on participants table';
  END IF;
  
  -- Check that we have the expected number of policies for participants
  SELECT COUNT(*) INTO policy_count
  FROM pg_policies 
  WHERE schemaname = 'public' 
  AND tablename = 'participants';
  
  IF policy_count < 3 THEN
    RAISE EXCEPTION 'Insufficient RLS policies on participants table: found %, expected at least 3', policy_count;
  END IF;
  
  -- Check that anonymous insert policy exists specifically
  IF NOT EXISTS(
    SELECT 1 FROM pg_policies 
    WHERE schemaname = 'public' 
    AND tablename = 'participants'
    AND policyname = 'Allow anonymous insert participants'
    AND roles = '{anon}'
  ) THEN
    RAISE EXCEPTION 'Critical policy missing: Allow anonymous insert participants';
  END IF;
  
  RAISE NOTICE 'SUCCESS: All RLS policies verified for production deployment';
END $$;

-- ============================================================================
-- STEP 6: CREATE INDEXES FOR PERFORMANCE
-- ============================================================================

-- Index for swipe lookups by participant (safe if already exists)
CREATE INDEX IF NOT EXISTS idx_swipes_participant ON public.swipes(participant_id);

-- Index for swipe lookups by design/card (safe if already exists) 
CREATE INDEX IF NOT EXISTS idx_swipes_card ON public.swipes(card_id);

-- ============================================================================
-- STEP 7: LOG SUCCESSFUL MIGRATION FOR DEBUGGING
-- ============================================================================

-- Insert a test record to verify the migration worked
-- This will fail if the policies aren't working correctly
INSERT INTO public.participants (email, answers, marketing_opt_in, is_complete) 
VALUES (
  'migration-test-0004@internal.test', 
  jsonb_build_object(
    'migration_id', '0004_fix_production_permissions_final',
    'timestamp', now()::text,
    'fix_description', 'Resolved HTTP 401 and PostgreSQL 42501 permission denied errors',
    'policies_applied', ARRAY['anonymous_insert', 'anonymous_read', 'authenticated_full_access'],
    'production_ready', true
  ),
  false,
  true
)
ON CONFLICT DO NOTHING;

-- Final success message
RAISE NOTICE 'MIGRATION 0004 COMPLETE: Production permission issues resolved. Survey submissions should now work without 401/42501 errors.';